--2.3
--1
DELETE	FROM CUSTOMERS
WHERE CITY = 'BOMBAY'
--2
DELETE FROM DEPOSIT
WHERE AMOUNT<=1000
--3
DELETE FROM BORROW
WHERE BNAME = 'AJNI'
--4
DELETE FROM BORROW
WHERE LOANNO <=210 AND LOANNO >=201
--5
DELETE FROM DEPOSIT
WHERE ADATE>'1-12-1996'
--6
TRUNCATE TABLE CUSTOMERS
--7
DELETE FROM DEPOSIT
WHERE CNAME='ANIL' AND ACTNO=101
--8
DELETE FROM DEPOSIT
WHERE BNAME <> 'ANDHERI'
--9
DELETE FROM BORROW
WHERE AMOUNT <= 2000 AND BNAME <> 'VRICE'
--10
DROP TABLE BRANCH