--LAB 03

--1--
ALTER TABLE Student
ADD CITY varchar(20) NULL , BACKLOG INT NOT NULL

--2--
ALTER TABLE Student
ALTER COLUMN NAME VARCHAR (35)

--3--
ALTER TABLE STUDENT
ALTER COLUMN CPI INT

--4--
SP_RENAME 'STUDENT.ENROLLMENT_NO','ENO'


--5--
ALTER TABLE STUDENT
DROP COLUMN CITY

--6--
SP_RENAME STUDENT,STUDENT_MASTER

--7--
ALTER TABLE STUDENT
DROP COLUMN BACKLOG

--8--
ALTER TABLE STUDENT
ALTER COLUMN NAME VARCHAR (35) NOT NULL

--9--
SP_RENAME 'STUDENT_MASTER.BIRTHDATE','BDate'

--10--
ALTER TABLE STUDENT_MASTER
ALTER COLUMN ENO VARCHAR(12)

SELECT * FROM STUDENT_MASTER