--lab 2.2
--1
update DEPOSIT set AMOUNT = 5000
where AMOUNT = 3000
--2
UPDATE BORROW SET BNAME = 'C.G. ROAD'
WHERE BNAME='VRICE'AND CNAME = 'ANIL'
--3
UPDATE DEPOSIT SET ACTNO = 111,AMOUNT = 5000
WHERE CNAME = 'SANDIP'
--4
 UPDATE BORROW SET AMOUNT = AMOUNT+(.10 * AMOUNT)
--5
UPDATE DEPOSIT SET AMOUNT = 5000
WHERE ACTNO BETWEEN 103 AND 107
--6
UPDATE BORROW SET AMOUNT = NULL 
WHERE LOANNO = 321
--7
UPDATE BORROW SET LOANNO = 401,BNAME = 'AJNI'
WHERE LOANNO = 201 OR BNAME = 'VRICE' 
--8
UPDATE CUSTOMERS SET CNAME = 'ANIL JAIN'
WHERE CNAME = 'ANIL'  
--9
UPDATE DEPOSIT SET CNAME='RAMESH',BNAME='VRCE',AMOUNT=5000
WHERE ACTNO=102
--10
UPDATE BORROW SET BNAME = NULL , AMOUNT = NULL
WHERE LOANNO=481 AND CNAME='KRANTI'